### ISSUE TITLE
Use Github Actions For CI Workflow

### ISSUE THREAD

**Issue by nickdibari** [Moody-Tunes/moodytunes#440]
Currently we use Travis CI for our Continuous Integration solution. This enables us to run tests, linters, and other tools automatically when pull requests are opened for the project to build confidence in our releases. Recently there have been a number of issues with the integration between Travis and our repository, where pull request status was not properly updated after a build on Travis. This blocks our PRs from being merged, and removing the integration would reduce the confidence in our releases.

We should migrate over to running our CI through [Github Actions](https://help.github.com/en/actions). This will run our tests and checks through a Github action runner instead of a Travis instance and update the PR accordingly. This seems like a simpler approach as we'd be doing everything in Github, without the need for integrations or webhooks with a third party source. See this guide for transitioning Travis CI to Github Actions: https://github.com/anapaulagomes/from-travis-to-github-actions

Deliverables
- Continuous Integration workflow is performed through Github Actions
- No changes in new CI workflow

**Comment by nickdibari** [comment]
NOTES

Current CI workflow with Travis:

```yaml
targets: master, production

env:
  - DJANGO_SECRET_KEY: test_secret_key
  - DJANGO_SETTINGS_MODULE: mtdj.settings.test
  - MTDJ_ENV_FILE: test

before_install: Set up postgresql

install: 
  - pip install -r requirements/common.txt
  - pre-commit install

script:
  - pytest
  - flake8
  - pre-commit run --from-ref origin/HEAD --to-ref HEAD
  - importanize --config=.importanize.json --ci
```
