### ISSUE TITLE
Investigate Usage Of Compiled Style Sheets

### ISSUE THREAD

**Issue by nickdibari** [Moody-Tunes/moodytunes#90]
We want to use some precompiler for our stylesheets to make them easier to write. This will allow us to create more efficient and cleaner files for styling our site.

We should choose something that provides variables and allows for nested rules, like the following:

```css
.myClass {
    padding: 50px;
    
    .myInnerClass {
         // Nest rules inside of other rules
         background-color: blue;
    }
}
```

We might also want to compress our static files, especially the Javascript sources. Obfuscating the backend calls the client makes is good practice for making it tricky for someone to reverse engineer our stack. Something like [django-compressor](https://django-compressor.readthedocs.io/en/stable/) would be suitable.

Some ideas:
- [LESS](http://lesscss.org/)
- [SASS](https://sass-lang.com/documentation/file.SASS_REFERENCE.html)

Deliverables
- Plan of action for incorporating a pre-compiler for style sheets in mtdj
